//! HEALER Agent — auto-correction using Gemini for diagnosis and fix.
//!
//! The HEALER Agent monitors agent failures and attempts automatic correction:
//! 1. Diagnoses failures using Gemini AI analysis of error logs and recent messages
//! 2. Tests proposed fixes in an isolated sandbox with 5 test queries
//! 3. Applies fixes via atomic deploy, with rollback on failure
//! 4. Rate-limits attempts to max 3 per agent per hour (sliding window)

use std::collections::HashMap;
use std::future::Future;

use serde::{Deserialize, Serialize};

// =============================================================================
// Types
// =============================================================================

/// Diagnosis produced by Gemini analysis of an agent failure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealerDiagnosis {
    /// The agent that failed.
    pub agent_id: String,
    /// Error logs collected from the failing agent.
    pub error_logs: Vec<String>,
    /// Last messages processed by the agent (up to 10).
    pub last_messages: Vec<String>,
    /// The proposed fix generated by Gemini analysis.
    pub proposed_fix: String,
}

/// Errors that can occur during healing operations.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum HealerError {
    #[error("rate limit exceeded for agent {0}: max {1} attempts per hour")]
    RateLimitExceeded(String, u8),
    #[error("diagnosis failed for agent {0}: {1}")]
    DiagnosisFailed(String, String),
    #[error("sandbox test failed for agent {0}")]
    SandboxTestFailed(String),
    #[error("deployment failed for agent {0}: {1}")]
    DeployFailed(String, String),
    #[error("rollback failed for agent {0}: {1}")]
    RollbackFailed(String, String),
}

// =============================================================================
// Traits (for mockability)
// =============================================================================

/// Trait for Gemini-based failure analysis.
/// Allows mocking the AI analysis in tests.
pub trait GeminiAnalyzer: Send + Sync {
    /// Analyze agent failure using error logs, last messages, and agent state.
    /// Returns a diagnosis with a proposed fix.
    fn analyze_failure(
        &self,
        agent_id: &str,
        error_logs: &[String],
        last_messages: &[String],
    ) -> impl Future<Output = Result<HealerDiagnosis, HealerError>> + Send;
}

/// Trait for sandbox-based fix testing.
/// Allows mocking the sandbox environment in tests.
pub trait HealerSandbox: Send + Sync {
    /// Test a proposed fix in an isolated sandbox with the given number of test queries.
    /// Returns true if all test queries pass.
    fn test_fix_in_sandbox(
        &self,
        diagnosis: &HealerDiagnosis,
        test_queries: usize,
    ) -> impl Future<Output = Result<bool, HealerError>> + Send;
}

/// Trait for atomic deployment and rollback.
/// Allows mocking the deployment process in tests.
pub trait HealerDeployer: Send + Sync {
    /// Atomically deploy the proposed fix for the given agent.
    fn atomic_deploy(
        &self,
        agent_id: &str,
        proposed_fix: &str,
    ) -> impl Future<Output = Result<(), HealerError>> + Send;

    /// Rollback the last deployment for the given agent.
    fn rollback(
        &self,
        agent_id: &str,
    ) -> impl Future<Output = Result<(), HealerError>> + Send;
}

// =============================================================================
// HealerAgent
// =============================================================================

/// Number of test queries to run in sandbox validation.
const SANDBOX_TEST_QUERIES: usize = 5;

/// Duration of the sliding window for rate limiting (1 hour in seconds).
const RATE_LIMIT_WINDOW_SECS: u64 = 3600;

/// The HEALER Agent that orchestrates auto-correction of failing agents.
///
/// Rate-limits healing attempts to `max_attempts_per_hour` per agent using
/// a sliding window approach.
pub struct HealerAgent<A, S, D>
where
    A: GeminiAnalyzer,
    S: HealerSandbox,
    D: HealerDeployer,
{
    /// Maximum healing attempts allowed per agent per hour.
    pub max_attempts_per_hour: u8,
    /// Tracks timestamps (Unix seconds) of healing attempts per agent.
    pub attempt_tracker: HashMap<String, Vec<u64>>,
    /// Gemini analyzer for diagnosing failures.
    analyzer: A,
    /// Sandbox for testing proposed fixes.
    sandbox: S,
    /// Deployer for atomic deploy and rollback.
    deployer: D,
}

impl<A, S, D> HealerAgent<A, S, D>
where
    A: GeminiAnalyzer,
    S: HealerSandbox,
    D: HealerDeployer,
{
    /// Create a new HealerAgent with the given dependencies.
    pub fn new(analyzer: A, sandbox: S, deployer: D) -> Self {
        Self {
            max_attempts_per_hour: 3,
            attempt_tracker: HashMap::new(),
            analyzer,
            sandbox,
            deployer,
        }
    }

    /// Check if the agent has not exceeded the max attempts per hour.
    ///
    /// Uses a sliding window: counts attempts within the last 60 minutes
    /// from `now_secs`. Returns `true` if a new attempt is allowed.
    pub fn can_attempt(&self, agent_id: &str, now_secs: u64) -> bool {
        let window_start = now_secs.saturating_sub(RATE_LIMIT_WINDOW_SECS);

        match self.attempt_tracker.get(agent_id) {
            Some(timestamps) => {
                let recent_count = timestamps
                    .iter()
                    .filter(|&&ts| ts > window_start)
                    .count();
                recent_count < self.max_attempts_per_hour as usize
            }
            None => true,
        }
    }

    /// Record a healing attempt for the given agent at the specified time.
    fn record_attempt(&mut self, agent_id: &str, now_secs: u64) {
        let timestamps = self
            .attempt_tracker
            .entry(agent_id.to_string())
            .or_default();
        timestamps.push(now_secs);

        // Prune old entries outside the window to prevent unbounded growth.
        let window_start = now_secs.saturating_sub(RATE_LIMIT_WINDOW_SECS);
        timestamps.retain(|&ts| ts > window_start);
    }

    /// Diagnose an agent failure using Gemini analysis.
    ///
    /// Analyzes error logs and the last 10 messages to produce a diagnosis
    /// with a proposed fix.
    pub async fn diagnose(
        &self,
        agent_id: &str,
        error_logs: &[String],
        last_messages: &[String],
    ) -> Result<HealerDiagnosis, HealerError> {
        // Take at most the last 10 messages for analysis.
        let messages: Vec<String> = last_messages
            .iter()
            .rev()
            .take(10)
            .rev()
            .cloned()
            .collect();

        self.analyzer
            .analyze_failure(agent_id, error_logs, &messages)
            .await
    }

    /// Test a proposed fix in an isolated sandbox with 5 test queries.
    ///
    /// Returns `true` if all test queries pass in the sandbox.
    pub async fn test_fix(
        &self,
        diagnosis: &HealerDiagnosis,
    ) -> Result<bool, HealerError> {
        self.sandbox
            .test_fix_in_sandbox(diagnosis, SANDBOX_TEST_QUERIES)
            .await
    }

    /// Apply a fix via atomic deploy if sandbox test passes, rollback if it fails.
    ///
    /// This method:
    /// 1. Checks rate limit
    /// 2. Deploys the fix atomically
    /// 3. Rolls back on deployment failure
    pub async fn apply_fix(
        &mut self,
        diagnosis: &HealerDiagnosis,
        now_secs: u64,
    ) -> Result<(), HealerError> {
        let agent_id = &diagnosis.agent_id;

        // Check rate limit before attempting.
        if !self.can_attempt(agent_id, now_secs) {
            return Err(HealerError::RateLimitExceeded(
                agent_id.clone(),
                self.max_attempts_per_hour,
            ));
        }

        // Record the attempt.
        self.record_attempt(agent_id, now_secs);

        // Attempt atomic deploy.
        match self
            .deployer
            .atomic_deploy(agent_id, &diagnosis.proposed_fix)
            .await
        {
            Ok(()) => Ok(()),
            Err(deploy_err) => {
                // Rollback on failure (best-effort).
                let _ = self.deployer.rollback(agent_id).await;
                Err(deploy_err)
            }
        }
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // =========================================================================
    // Mock implementations for testing
    // =========================================================================

    struct MockAnalyzer;

    impl MockAnalyzer {
        fn new() -> Self {
            Self
        }
    }

    impl GeminiAnalyzer for MockAnalyzer {
        async fn analyze_failure(
            &self,
            agent_id: &str,
            error_logs: &[String],
            _last_messages: &[String],
        ) -> Result<HealerDiagnosis, HealerError> {
            Ok(HealerDiagnosis {
                agent_id: agent_id.to_string(),
                error_logs: error_logs.to_vec(),
                last_messages: vec![],
                proposed_fix: "restart service".to_string(),
            })
        }
    }

    struct MockSandbox {
        pass: bool,
    }

    impl MockSandbox {
        fn new(pass: bool) -> Self {
            Self { pass }
        }
    }

    impl HealerSandbox for MockSandbox {
        async fn test_fix_in_sandbox(
            &self,
            _diagnosis: &HealerDiagnosis,
            _test_queries: usize,
        ) -> Result<bool, HealerError> {
            Ok(self.pass)
        }
    }

    struct MockDeployer {
        should_fail: bool,
    }

    impl MockDeployer {
        fn new(should_fail: bool) -> Self {
            Self { should_fail }
        }
    }

    impl HealerDeployer for MockDeployer {
        async fn atomic_deploy(
            &self,
            agent_id: &str,
            _proposed_fix: &str,
        ) -> Result<(), HealerError> {
            if self.should_fail {
                Err(HealerError::DeployFailed(
                    agent_id.to_string(),
                    "mock deploy failure".to_string(),
                ))
            } else {
                Ok(())
            }
        }

        async fn rollback(&self, _agent_id: &str) -> Result<(), HealerError> {
            Ok(())
        }
    }

    // =========================================================================
    // Rate limiting tests
    // =========================================================================

    #[test]
    fn test_can_attempt_no_prior_attempts() {
        let healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        assert!(healer.can_attempt("agent-1", 1000));
    }

    #[test]
    fn test_can_attempt_under_limit() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        // Record 2 attempts within the window.
        healer.record_attempt("agent-1", 1000);
        healer.record_attempt("agent-1", 2000);

        // Should still allow a 3rd attempt.
        assert!(healer.can_attempt("agent-1", 3000));
    }

    #[test]
    fn test_can_attempt_at_limit() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        // Record 3 attempts within the window.
        healer.record_attempt("agent-1", 1000);
        healer.record_attempt("agent-1", 2000);
        healer.record_attempt("agent-1", 3000);

        // 4th attempt should be rejected.
        assert!(!healer.can_attempt("agent-1", 3500));
    }

    #[test]
    fn test_can_attempt_after_window_expires() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        // Record 3 attempts at time 1000, 1500, 2000.
        healer.record_attempt("agent-1", 1000);
        healer.record_attempt("agent-1", 1500);
        healer.record_attempt("agent-1", 2000);

        // After 1 hour (3600s), the window has slid past the first attempt.
        // now = 4601 means window_start = 4601 - 3600 = 1001
        // Attempts at 1000 are outside (not > 1001), 1500 and 2000 are inside → 2 attempts.
        assert!(healer.can_attempt("agent-1", 4601));
    }

    #[test]
    fn test_can_attempt_sliding_window_partial_expiry() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        // Attempts at t=100, t=200, t=300.
        healer.record_attempt("agent-1", 100);
        healer.record_attempt("agent-1", 200);
        healer.record_attempt("agent-1", 300);

        // At t=3701, window_start = 3701 - 3600 = 101.
        // Only t=200 and t=300 are > 101 → 2 attempts, allow 3rd.
        assert!(healer.can_attempt("agent-1", 3701));

        // At t=3700, window_start = 3700 - 3600 = 100.
        // t=100 is NOT > 100 (equal), so excluded. t=200, t=300 in window → 2 attempts.
        assert!(healer.can_attempt("agent-1", 3700));
    }

    #[test]
    fn test_can_attempt_different_agents_independent() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        // Max out agent-1.
        healer.record_attempt("agent-1", 1000);
        healer.record_attempt("agent-1", 2000);
        healer.record_attempt("agent-1", 3000);

        // agent-1 is at limit.
        assert!(!healer.can_attempt("agent-1", 3500));
        // agent-2 is independent and has no attempts.
        assert!(healer.can_attempt("agent-2", 3500));
    }

    #[test]
    fn test_record_attempt_prunes_old_entries() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );
        // Record old attempts.
        healer.record_attempt("agent-1", 100);
        healer.record_attempt("agent-1", 200);

        // Record a new attempt far in the future — old ones should be pruned.
        healer.record_attempt("agent-1", 5000);

        let timestamps = healer.attempt_tracker.get("agent-1").unwrap();
        // Only the recent one (5000) should remain since window_start = 5000 - 3600 = 1400.
        assert_eq!(timestamps.len(), 1);
        assert_eq!(timestamps[0], 5000);
    }

    #[tokio::test]
    async fn test_apply_fix_respects_rate_limit() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );

        let diagnosis = HealerDiagnosis {
            agent_id: "agent-1".to_string(),
            error_logs: vec!["error".to_string()],
            last_messages: vec![],
            proposed_fix: "fix".to_string(),
        };

        // First 3 attempts should succeed.
        assert!(healer.apply_fix(&diagnosis, 1000).await.is_ok());
        assert!(healer.apply_fix(&diagnosis, 2000).await.is_ok());
        assert!(healer.apply_fix(&diagnosis, 3000).await.is_ok());

        // 4th attempt within the hour should fail with rate limit error.
        let result = healer.apply_fix(&diagnosis, 3500).await;
        assert!(matches!(result, Err(HealerError::RateLimitExceeded(_, 3))));
    }

    #[tokio::test]
    async fn test_apply_fix_rollback_on_deploy_failure() {
        let mut healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(true), // deployer will fail
        );

        let diagnosis = HealerDiagnosis {
            agent_id: "agent-1".to_string(),
            error_logs: vec![],
            last_messages: vec![],
            proposed_fix: "bad fix".to_string(),
        };

        let result = healer.apply_fix(&diagnosis, 1000).await;
        assert!(matches!(result, Err(HealerError::DeployFailed(_, _))));
    }

    #[tokio::test]
    async fn test_diagnose_limits_to_last_10_messages() {
        let healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );

        let messages: Vec<String> = (0..20).map(|i| format!("msg-{}", i)).collect();
        let errors = vec!["error".to_string()];

        let diagnosis = healer.diagnose("agent-1", &errors, &messages).await.unwrap();
        assert_eq!(diagnosis.agent_id, "agent-1");
    }

    #[tokio::test]
    async fn test_test_fix_passes() {
        let healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(true),
            MockDeployer::new(false),
        );

        let diagnosis = HealerDiagnosis {
            agent_id: "agent-1".to_string(),
            error_logs: vec![],
            last_messages: vec![],
            proposed_fix: "fix".to_string(),
        };

        assert!(healer.test_fix(&diagnosis).await.unwrap());
    }

    #[tokio::test]
    async fn test_test_fix_fails() {
        let healer = HealerAgent::new(
            MockAnalyzer::new(),
            MockSandbox::new(false), // sandbox will report failure
            MockDeployer::new(false),
        );

        let diagnosis = HealerDiagnosis {
            agent_id: "agent-1".to_string(),
            error_logs: vec![],
            last_messages: vec![],
            proposed_fix: "bad fix".to_string(),
        };

        assert!(!healer.test_fix(&diagnosis).await.unwrap());
    }
}
