//! SHIELD Agent — real-time monitoring of all agent actions.
//!
//! Provides:
//! - Credential exposure detection (pattern matching for known secret formats)
//! - Rate limiting (100 actions/min per agent)
//! - Anomaly detection (rolling 24-hour baseline, >2 std deviations)

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};

// =============================================================================
// AgentId (local copy for crate independence)
// =============================================================================

/// Unique identifier for an agent in the system.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgentId(pub String);

impl AgentId {
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for AgentId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<&str> for AgentId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl From<String> for AgentId {
    fn from(s: String) -> Self {
        Self(s)
    }
}

// =============================================================================
// BusMessage (local definition for crate independence)
// =============================================================================

/// A message on the bus, used by SHIELD for observation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BusMessage {
    pub id: String,
    pub sender_id: AgentId,
    pub destination_id: AgentId,
    pub task_type: String,
    pub payload: Vec<u8>,
    pub timestamp: u64,
}

// =============================================================================
// Security Alert
// =============================================================================

/// Severity levels for security alerts.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// Types of security alerts the SHIELD agent can raise.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertType {
    CredentialExposure,
    RateLimitExceeded,
    AnomalyDetected,
}

/// A security alert generated by the SHIELD agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityAlert {
    pub alert_type: AlertType,
    pub agent_id: AgentId,
    pub severity: AlertSeverity,
    pub details: String,
    pub timestamp: u64,
}

// =============================================================================
// Rate Counter
// =============================================================================

/// Tracks actions per agent within a sliding 60-second window.
/// Stores timestamps (in seconds) of each action in a VecDeque.
#[derive(Debug, Clone)]
pub struct RateCounter {
    /// Timestamps (unix seconds) of actions within the current window.
    pub actions: VecDeque<u64>,
}

impl RateCounter {
    pub fn new() -> Self {
        Self {
            actions: VecDeque::new(),
        }
    }

    /// Record an action at the given timestamp and prune expired entries.
    pub fn record_action(&mut self, timestamp_secs: u64) {
        // Remove actions older than 60 seconds
        let cutoff = timestamp_secs.saturating_sub(60);
        while let Some(&front) = self.actions.front() {
            if front <= cutoff {
                self.actions.pop_front();
            } else {
                break;
            }
        }
        self.actions.push_back(timestamp_secs);
    }

    /// Returns the number of actions in the current 60-second window.
    pub fn count(&self, current_timestamp_secs: u64) -> usize {
        let cutoff = current_timestamp_secs.saturating_sub(60);
        self.actions.iter().filter(|&&t| t > cutoff).count()
    }
}

impl Default for RateCounter {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Rolling Baseline (Anomaly Detection)
// =============================================================================

/// A rolling baseline over a configurable window (default 24 hours).
/// Maintains data points and computes mean and standard deviation for anomaly detection.
#[derive(Debug, Clone)]
pub struct RollingBaseline {
    /// Window size in hours.
    pub window_hours: u32,
    /// Data points within the rolling window.
    pub data_points: Vec<f64>,
    /// Current mean of data points.
    pub mean: f64,
    /// Current standard deviation of data points.
    pub std_dev: f64,
}

impl RollingBaseline {
    /// Create a new rolling baseline with a 24-hour window.
    pub fn new() -> Self {
        Self {
            window_hours: 24,
            data_points: Vec::new(),
            mean: 0.0,
            std_dev: 0.0,
        }
    }

    /// Create a rolling baseline with a custom window size.
    pub fn with_window(window_hours: u32) -> Self {
        Self {
            window_hours,
            data_points: Vec::new(),
            mean: 0.0,
            std_dev: 0.0,
        }
    }

    /// Add a data point and recompute statistics.
    pub fn add_data_point(&mut self, value: f64) {
        self.data_points.push(value);
        self.recompute_stats();
    }

    /// Recompute mean and standard deviation from current data points.
    fn recompute_stats(&mut self) {
        let n = self.data_points.len();
        if n == 0 {
            self.mean = 0.0;
            self.std_dev = 0.0;
            return;
        }

        let sum: f64 = self.data_points.iter().sum();
        self.mean = sum / n as f64;

        if n < 2 {
            self.std_dev = 0.0;
            return;
        }

        let variance: f64 = self
            .data_points
            .iter()
            .map(|&x| (x - self.mean).powi(2))
            .sum::<f64>()
            / n as f64;
        self.std_dev = variance.sqrt();
    }

    /// Check if a value is anomalous (>2 standard deviations from mean).
    /// Returns false if there are fewer than 2 data points (insufficient data).
    pub fn is_anomalous(&self, value: f64) -> bool {
        if self.data_points.len() < 2 || self.std_dev == 0.0 {
            return false;
        }
        let deviation = (value - self.mean).abs();
        deviation > 2.0 * self.std_dev
    }
}

impl Default for RollingBaseline {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Metric Point
// =============================================================================

/// A single metric observation for anomaly detection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricPoint {
    pub agent_id: AgentId,
    pub metric_name: String,
    pub value: f64,
    pub timestamp: u64,
}

// =============================================================================
// SHIELD Agent
// =============================================================================

/// Known credential/secret patterns to detect in message payloads.
const CREDENTIAL_PATTERNS: &[&str] = &[
    "sk-",       // OpenAI / Stripe secret keys
    "AKIA",      // AWS access key IDs
    "ghp_",      // GitHub personal access tokens
    "gho_",      // GitHub OAuth tokens
    "ghu_",      // GitHub user-to-server tokens
    "ghs_",      // GitHub server-to-server tokens
    "Bearer ",   // Bearer tokens in headers
    "bearer ",   // lowercase variant
];

/// The SHIELD Agent monitors all agent actions in real-time.
///
/// Responsibilities:
/// - Detect credential exposure in message payloads
/// - Enforce rate limits (100 actions/min per agent)
/// - Detect anomalies via rolling baseline (>2 std deviations)
#[derive(Debug)]
pub struct ShieldAgent {
    /// Rate limit counters per agent.
    pub rate_limits: HashMap<AgentId, RateCounter>,
    /// Rolling baseline for anomaly detection.
    pub anomaly_baseline: RollingBaseline,
}

impl ShieldAgent {
    /// Create a new ShieldAgent with default settings.
    pub fn new() -> Self {
        Self {
            rate_limits: HashMap::new(),
            anomaly_baseline: RollingBaseline::new(),
        }
    }

    /// Observe a bus message in real-time and return a security alert if a
    /// violation is detected.
    ///
    /// Checks (in order):
    /// 1. Credential exposure in payload
    /// 2. Rate limit exceeded for sender
    pub fn observe_message(&mut self, msg: &BusMessage) -> Option<SecurityAlert> {
        // Check for credential exposure
        if self.detect_credential_exposure(&msg.payload) {
            return Some(SecurityAlert {
                alert_type: AlertType::CredentialExposure,
                agent_id: msg.sender_id.clone(),
                severity: AlertSeverity::Critical,
                details: format!(
                    "Credential pattern detected in message {} from agent {}",
                    msg.id,
                    msg.sender_id.as_str()
                ),
                timestamp: msg.timestamp,
            });
        }

        // Check rate limit
        if self.check_rate_limit(&msg.sender_id, msg.timestamp) {
            return Some(SecurityAlert {
                alert_type: AlertType::RateLimitExceeded,
                agent_id: msg.sender_id.clone(),
                severity: AlertSeverity::High,
                details: format!(
                    "Agent {} exceeded rate limit of 100 actions/min",
                    msg.sender_id.as_str()
                ),
                timestamp: msg.timestamp,
            });
        }

        None
    }

    /// Detect credential exposure patterns in a message payload.
    ///
    /// Scans the payload (interpreted as UTF-8) for known secret patterns:
    /// `sk-`, `AKIA`, `ghp_`, `Bearer` tokens, etc.
    pub fn detect_credential_exposure(&self, payload: &[u8]) -> bool {
        // Try to interpret payload as UTF-8 text
        let text = match std::str::from_utf8(payload) {
            Ok(s) => s,
            Err(_) => return false, // Binary payload, skip text pattern matching
        };

        for pattern in CREDENTIAL_PATTERNS {
            if text.contains(pattern) {
                return true;
            }
        }

        false
    }

    /// Check if an agent exceeds the rate limit (100 actions/min).
    ///
    /// Records the action and returns `true` if the agent has exceeded
    /// 100 actions within the last 60 seconds (meaning it should be throttled).
    pub fn check_rate_limit(&mut self, agent_id: &AgentId, timestamp_ms: u64) -> bool {
        let timestamp_secs = timestamp_ms / 1000;
        let counter = self
            .rate_limits
            .entry(agent_id.clone())
            .or_insert_with(RateCounter::new);

        counter.record_action(timestamp_secs);
        counter.count(timestamp_secs) > 100
    }

    /// Update the anomaly baseline with a new metric data point.
    pub fn update_baseline(&mut self, metric: &MetricPoint) {
        self.anomaly_baseline.add_data_point(metric.value);
    }

    /// Detect if a metric point is anomalous (>2 standard deviations from baseline mean).
    ///
    /// Returns `true` if the value deviates more than 2 standard deviations
    /// from the rolling 24-hour baseline mean.
    pub fn detect_anomaly(&self, metric: &MetricPoint) -> bool {
        self.anomaly_baseline.is_anomalous(metric.value)
    }
}

impl Default for ShieldAgent {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn make_message(sender: &str, payload: &[u8], timestamp: u64) -> BusMessage {
        BusMessage {
            id: "msg-001".to_string(),
            sender_id: AgentId::new(sender),
            destination_id: AgentId::new("receiver"),
            task_type: "action".to_string(),
            payload: payload.to_vec(),
            timestamp,
        }
    }

    // -------------------------------------------------------------------------
    // SecurityAlert struct tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_security_alert_creation() {
        let alert = SecurityAlert {
            alert_type: AlertType::CredentialExposure,
            agent_id: AgentId::new("agent-1"),
            severity: AlertSeverity::Critical,
            details: "Test alert".to_string(),
            timestamp: 1700000000000,
        };
        assert_eq!(alert.alert_type, AlertType::CredentialExposure);
        assert_eq!(alert.agent_id.as_str(), "agent-1");
        assert_eq!(alert.severity, AlertSeverity::Critical);
    }

    // -------------------------------------------------------------------------
    // RateCounter tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_rate_counter_new_is_empty() {
        let counter = RateCounter::new();
        assert_eq!(counter.count(1000), 0);
    }

    #[test]
    fn test_rate_counter_records_actions() {
        let mut counter = RateCounter::new();
        counter.record_action(100);
        counter.record_action(110);
        counter.record_action(120);
        assert_eq!(counter.count(120), 3);
    }

    #[test]
    fn test_rate_counter_expires_old_actions() {
        let mut counter = RateCounter::new();
        counter.record_action(100);
        counter.record_action(110);
        // 61 seconds later, the first two should be expired
        counter.record_action(170);
        assert_eq!(counter.count(170), 1);
    }

    #[test]
    fn test_rate_counter_sliding_window() {
        let mut counter = RateCounter::new();
        // Add actions at t=1..60 (all within window at t=60)
        for t in 1..=60 {
            counter.record_action(t);
        }
        // At t=60, cutoff = 0, so all actions (t=1..60) satisfy t > 0
        assert_eq!(counter.count(60), 60);
        // At t=62, cutoff = 2, so actions at t=1 and t=2 are expired (t <= 2)
        assert_eq!(counter.count(62), 58);
    }

    // -------------------------------------------------------------------------
    // RollingBaseline tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_rolling_baseline_empty() {
        let baseline = RollingBaseline::new();
        assert_eq!(baseline.mean, 0.0);
        assert_eq!(baseline.std_dev, 0.0);
        assert_eq!(baseline.window_hours, 24);
    }

    #[test]
    fn test_rolling_baseline_single_point() {
        let mut baseline = RollingBaseline::new();
        baseline.add_data_point(10.0);
        assert_eq!(baseline.mean, 10.0);
        assert_eq!(baseline.std_dev, 0.0);
        // With only 1 point, nothing is anomalous
        assert!(!baseline.is_anomalous(100.0));
    }

    #[test]
    fn test_rolling_baseline_mean_and_std_dev() {
        let mut baseline = RollingBaseline::new();
        // Add points: 10, 10, 10, 10, 10 → mean=10, std_dev=0
        for _ in 0..5 {
            baseline.add_data_point(10.0);
        }
        assert!((baseline.mean - 10.0).abs() < f64::EPSILON);
        assert!((baseline.std_dev - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_rolling_baseline_detects_anomaly() {
        let mut baseline = RollingBaseline::new();
        // Build a baseline with values around 50 (std_dev ~0)
        for _ in 0..100 {
            baseline.add_data_point(50.0);
        }
        // Add a slight variation to get non-zero std_dev
        baseline.add_data_point(51.0);
        baseline.add_data_point(49.0);

        // Value of 50 should not be anomalous
        assert!(!baseline.is_anomalous(50.0));
        // Value far from mean should be anomalous
        assert!(baseline.is_anomalous(100.0));
        assert!(baseline.is_anomalous(0.0));
    }

    #[test]
    fn test_rolling_baseline_normal_variation_not_anomalous() {
        let mut baseline = RollingBaseline::new();
        // Build baseline with known distribution: mean=100, std_dev≈10
        let values = vec![90.0, 95.0, 100.0, 105.0, 110.0];
        for v in &values {
            baseline.add_data_point(*v);
        }
        // Values within 2 std devs should not be anomalous
        assert!(!baseline.is_anomalous(100.0));
        assert!(!baseline.is_anomalous(105.0));
    }

    // -------------------------------------------------------------------------
    // Credential exposure detection tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_detect_credential_openai_key() {
        let shield = ShieldAgent::new();
        let payload = b"Here is my key: sk-abc123def456";
        assert!(shield.detect_credential_exposure(payload));
    }

    #[test]
    fn test_detect_credential_aws_key() {
        let shield = ShieldAgent::new();
        let payload = b"AWS key: AKIAIOSFODNN7EXAMPLE";
        assert!(shield.detect_credential_exposure(payload));
    }

    #[test]
    fn test_detect_credential_github_token() {
        let shield = ShieldAgent::new();
        let payload = b"token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        assert!(shield.detect_credential_exposure(payload));
    }

    #[test]
    fn test_detect_credential_bearer_token() {
        let shield = ShieldAgent::new();
        let payload = b"Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.xxx";
        assert!(shield.detect_credential_exposure(payload));
    }

    #[test]
    fn test_no_credential_in_normal_payload() {
        let shield = ShieldAgent::new();
        let payload = b"Hello, this is a normal message with no secrets.";
        assert!(!shield.detect_credential_exposure(payload));
    }

    #[test]
    fn test_no_credential_in_binary_payload() {
        let shield = ShieldAgent::new();
        // Invalid UTF-8 bytes
        let payload: &[u8] = &[0xFF, 0xFE, 0xFD, 0xFC];
        assert!(!shield.detect_credential_exposure(payload));
    }

    // -------------------------------------------------------------------------
    // Rate limit tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_rate_limit_under_threshold() {
        let mut shield = ShieldAgent::new();
        let agent = AgentId::new("agent-1");
        let base_ts = 1700000000000u64; // milliseconds

        // 100 actions should be fine
        for i in 0..100 {
            let exceeded = shield.check_rate_limit(&agent, base_ts + i * 100);
            assert!(!exceeded, "Should not exceed at action {}", i + 1);
        }
    }

    #[test]
    fn test_rate_limit_exceeded_at_101() {
        let mut shield = ShieldAgent::new();
        let agent = AgentId::new("agent-1");
        let base_ts = 1700000000000u64; // milliseconds

        // First 100 actions within the same second window
        for i in 0..100 {
            shield.check_rate_limit(&agent, base_ts + i * 10);
        }
        // 101st action should trigger rate limit
        let exceeded = shield.check_rate_limit(&agent, base_ts + 1000);
        assert!(exceeded, "Should exceed rate limit at 101 actions");
    }

    #[test]
    fn test_rate_limit_resets_after_window() {
        let mut shield = ShieldAgent::new();
        let agent = AgentId::new("agent-1");
        let base_ts = 1700000000000u64;

        // Fill up 101 actions
        for i in 0..101 {
            shield.check_rate_limit(&agent, base_ts + i * 10);
        }

        // After 61 seconds, the window should have reset
        let new_ts = base_ts + 61_000;
        let exceeded = shield.check_rate_limit(&agent, new_ts);
        assert!(!exceeded, "Should not exceed after window reset");
    }

    // -------------------------------------------------------------------------
    // Anomaly detection tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_detect_anomaly_with_baseline() {
        let mut shield = ShieldAgent::new();

        // Build baseline around 50
        for _ in 0..50 {
            shield.update_baseline(&MetricPoint {
                agent_id: AgentId::new("agent-1"),
                metric_name: "cpu".to_string(),
                value: 50.0,
                timestamp: 1700000000000,
            });
        }
        // Add slight variation for non-zero std_dev
        shield.update_baseline(&MetricPoint {
            agent_id: AgentId::new("agent-1"),
            metric_name: "cpu".to_string(),
            value: 51.0,
            timestamp: 1700000000000,
        });
        shield.update_baseline(&MetricPoint {
            agent_id: AgentId::new("agent-1"),
            metric_name: "cpu".to_string(),
            value: 49.0,
            timestamp: 1700000000000,
        });

        // Normal value should not be anomalous
        let normal = MetricPoint {
            agent_id: AgentId::new("agent-1"),
            metric_name: "cpu".to_string(),
            value: 50.0,
            timestamp: 1700000000000,
        };
        assert!(!shield.detect_anomaly(&normal));

        // Extreme value should be anomalous
        let anomalous = MetricPoint {
            agent_id: AgentId::new("agent-1"),
            metric_name: "cpu".to_string(),
            value: 200.0,
            timestamp: 1700000000000,
        };
        assert!(shield.detect_anomaly(&anomalous));
    }

    #[test]
    fn test_detect_anomaly_insufficient_data() {
        let shield = ShieldAgent::new();
        // With no baseline data, nothing should be flagged
        let metric = MetricPoint {
            agent_id: AgentId::new("agent-1"),
            metric_name: "cpu".to_string(),
            value: 999.0,
            timestamp: 1700000000000,
        };
        assert!(!shield.detect_anomaly(&metric));
    }

    // -------------------------------------------------------------------------
    // observe_message integration tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_observe_message_detects_credential() {
        let mut shield = ShieldAgent::new();
        let msg = make_message("agent-1", b"my key is sk-secret123", 1700000000000);

        let alert = shield.observe_message(&msg);
        assert!(alert.is_some());
        let alert = alert.unwrap();
        assert_eq!(alert.alert_type, AlertType::CredentialExposure);
        assert_eq!(alert.severity, AlertSeverity::Critical);
    }

    #[test]
    fn test_observe_message_detects_rate_limit() {
        let mut shield = ShieldAgent::new();
        let base_ts = 1700000000000u64;

        // Send 100 normal messages (no credential, within rate limit)
        for i in 0..100 {
            let msg = make_message("agent-1", b"normal payload", base_ts + i * 10);
            let alert = shield.observe_message(&msg);
            assert!(alert.is_none(), "Should not alert at message {}", i + 1);
        }

        // 101st message should trigger rate limit
        let msg = make_message("agent-1", b"normal payload", base_ts + 1000);
        let alert = shield.observe_message(&msg);
        assert!(alert.is_some());
        let alert = alert.unwrap();
        assert_eq!(alert.alert_type, AlertType::RateLimitExceeded);
        assert_eq!(alert.severity, AlertSeverity::High);
    }

    #[test]
    fn test_observe_message_no_alert_for_normal() {
        let mut shield = ShieldAgent::new();
        let msg = make_message("agent-1", b"Hello world", 1700000000000);

        let alert = shield.observe_message(&msg);
        assert!(alert.is_none());
    }
}
